#!/usr/bin/env python3
"""Regenerate the "Community additions" table in docs/index.html.

Reads the community (non-first-party) entries from ecosystem/registry.yaml and
writes their rows between the COMMUNITY_ROWS:START/END markers in
docs/index.html, so a new entry in the registry shows up on the site without
any manual HTML editing. Descriptions are rendered as authored in the registry
(English) regardless of site language — like ecosystem/CATALOG.md, this table
isn't translated per entry.

Usage:
    python scripts/render_community_table.py            # write docs/index.html
    python scripts/render_community_table.py --check     # fail if out of date
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: `uv pip install -e '.[dev]'` (or `pip install pyyaml`).")

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "ecosystem" / "registry.yaml"
INDEX = ROOT / "docs" / "index.html"

START = "<!-- COMMUNITY_ROWS:START — generated by scripts/render_community_table.py from ecosystem/registry.yaml. Do not edit by hand; run the script instead. -->"
END = "<!-- COMMUNITY_ROWS:END -->"


def load_community_entries() -> list[dict]:
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    entries = data.get("entries", [])
    community = [e for e in entries if not e.get("first_party")]
    return sorted(community, key=lambda e: e["name"])


def render_row(entry: dict) -> str:
    name = html.escape(entry["name"])
    link = entry.get("repo") or entry.get("homepage") or ""
    desc = html.escape(" ".join(entry["description"].split()))
    author = html.escape(entry["author"])
    name_cell = f'<a href="{html.escape(link)}" target="_blank" rel="noopener">{name}</a>' if link else name
    return (
        f'<tr><td class="skill-name">{name_cell}</td>'
        f'<td class="skill-desc">{desc}</td>'
        f"<td>{author}</td></tr>"
    )


def render(entries: list[dict]) -> str:
    rows = "\n        ".join(render_row(e) for e in entries)
    return f"{START}\n        {rows}\n        {END}"


def main() -> None:
    check = "--check" in sys.argv
    entries = load_community_entries()
    block = render(entries)

    current = INDEX.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(current):
        sys.exit(f"Could not find COMMUNITY_ROWS markers in {INDEX.relative_to(ROOT)}.")
    updated = pattern.sub(block, current)

    if check:
        if updated != current:
            sys.exit(
                f"{INDEX.relative_to(ROOT)} is out of date. "
                "Run: python scripts/render_community_table.py"
            )
        print("Community table up to date.")
        return

    INDEX.write_text(updated, encoding="utf-8")
    print(f"Wrote {len(entries)} community entries to {INDEX.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
