#!/usr/bin/env python3
"""Regenerate the "Community additions" table in docs/index.html.

Reads the community (non-first-party) entries from ecosystem/registry.yaml and
writes their rows between the COMMUNITY_ROWS:START/END markers in
docs/index.html, and their English translations between the
COMMUNITY_I18N:START/END markers in the page's EN i18n object — so a new
entry in the registry shows up on the site, in both languages, without any
manual HTML/JS editing. Each community entry needs both `description`
(English) and `description_fi` (Finnish) in the registry.

Usage:
    python scripts/render_community_table.py            # write docs/index.html
    python scripts/render_community_table.py --check     # fail if out of date
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: `uv pip install -e '.[dev]'` (or `pip install pyyaml`).")

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "ecosystem" / "registry.yaml"
INDEX = ROOT / "docs" / "index.html"

ROWS_START = "<!-- COMMUNITY_ROWS:START — generated by scripts/render_community_table.py from ecosystem/registry.yaml. Do not edit by hand; run the script instead. -->"
ROWS_END = "<!-- COMMUNITY_ROWS:END -->"
I18N_START = "// COMMUNITY_I18N:START — generated by scripts/render_community_table.py from ecosystem/registry.yaml. Do not edit by hand; run the script instead."
I18N_END = "// COMMUNITY_I18N:END"


def load_community_entries() -> list[dict]:
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    entries = data.get("entries", [])
    community = [e for e in entries if not e.get("first_party")]
    for e in community:
        if not e.get("description_fi"):
            sys.exit(f"[{e['id']}] community entries need a 'description_fi' field.")
    return sorted(community, key=lambda e: e["name"])


def i18n_key(entry: dict) -> str:
    return f"community.{entry['id']}"


def render_row(entry: dict) -> str:
    name = html.escape(entry["name"])
    link = entry.get("repo") or entry.get("homepage") or ""
    desc_fi = html.escape(" ".join(entry["description_fi"].split()))
    author = html.escape(entry["author"])
    name_cell = f'<a href="{html.escape(link)}" target="_blank" rel="noopener">{name}</a>' if link else name
    return (
        f'<tr><td class="skill-name">{name_cell}</td>'
        f'<td class="skill-desc" data-i18n="{i18n_key(entry)}">{desc_fi}</td>'
        f"<td>{author}</td></tr>"
    )


def render_rows(entries: list[dict]) -> str:
    rows = "\n        ".join(render_row(e) for e in entries)
    return f"{ROWS_START}\n        {rows}\n        {ROWS_END}"


def render_i18n(entries: list[dict]) -> str:
    lines = "\n    ".join(
        f"'{i18n_key(e)}': {json.dumps(' '.join(e['description'].split()), ensure_ascii=False)},"
        for e in entries
    )
    return f"{I18N_START}\n    {lines}\n    {I18N_END}"


def substitute(text: str, start: str, end: str, block: str, label: str) -> str:
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        sys.exit(f"Could not find {label} markers in {INDEX.relative_to(ROOT)}.")
    return pattern.sub(block, text)


def main() -> None:
    check = "--check" in sys.argv
    entries = load_community_entries()

    current = INDEX.read_text(encoding="utf-8")
    updated = substitute(current, ROWS_START, ROWS_END, render_rows(entries), "COMMUNITY_ROWS")
    updated = substitute(updated, I18N_START, I18N_END, render_i18n(entries), "COMMUNITY_I18N")

    if check:
        if updated != current:
            sys.exit(
                f"{INDEX.relative_to(ROOT)} is out of date. "
                "Run: python scripts/render_community_table.py"
            )
        print("Community table up to date.")
        return

    INDEX.write_text(updated, encoding="utf-8")
    print(f"Wrote {len(entries)} community entries to {INDEX.relative_to(ROOT)} (FI + EN).")


if __name__ == "__main__":
    main()
